version: "3.9"
services:
  app1:
    build: app1/.
    ports:
      - "5000:5000"

  app2:
    build: app2/.
    ports:
      - "5001:5000"
    depends_on:
      - app1  

  redis:
    image: "redis:alpine"

  percona:
    image: percona/percona-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6603:3306
    
  lb:
    build: lb/.
    depends_on:
      - app1
      - app2
      - percona
      - redis
    ports:
      - 80:80
